-- JWB STUDIO Supabase setup
-- Run in Supabase Dashboard > SQL Editor. Create the administrator account in
-- Authentication > Users before using admin-login.html. Then assign the
-- app_metadata role below using the Dashboard SQL Editor (replace the email):
-- update auth.users
-- set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb
-- where email = 'YOUR_ADMIN_EMAIL';

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 160),
  content text not null check (char_length(content) between 1 and 10000),
  category text not null default '공지사항',
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Keep existing Supabase projects compatible when this setup file is rerun.
alter table public.notices add column if not exists category text not null default '공지사항';
alter table public.notices add column if not exists attachments jsonb not null default '[]'::jsonb;

alter table public.notices enable row level security;
drop policy if exists "Published notices are public" on public.notices;
create policy "Published notices are public"
  on public.notices for select to anon, authenticated using (true);
drop policy if exists "Authenticated admins manage notices" on public.notices;
create policy "Authenticated admins manage notices"
  on public.notices for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.portfolios (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  youtube text not null default '',
  description text not null default '',
  period text not null default '',
  role text not null default '',
  tools text not null default '',
  objective text not null default '',
  process text not null default '',
  outcome text not null default '',
  created_at timestamptz not null default now()
);

alter table public.portfolios add column if not exists youtube text not null default '';
alter table public.portfolios add column if not exists period text not null default '';
alter table public.portfolios add column if not exists role text not null default '';
alter table public.portfolios add column if not exists tools text not null default '';
alter table public.portfolios add column if not exists objective text not null default '';
alter table public.portfolios add column if not exists process text not null default '';
alter table public.portfolios add column if not exists outcome text not null default '';
alter table public.portfolios add column if not exists media_path text not null default '';
alter table public.portfolios add column if not exists media_type text not null default '';
alter table public.portfolios add column if not exists drive_file_id text not null default '';
alter table public.portfolios add column if not exists drive_url text not null default '';
alter table public.portfolios add column if not exists thumb_drive_file_id text not null default '';
alter table public.portfolios add column if not exists thumb_drive_url text not null default '';
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'portfolios' and column_name = 'thumb') then
    execute 'alter table public.portfolios alter column thumb set default ' || quote_literal('');
  end if;
end $$;

alter table public.portfolios enable row level security;
drop policy if exists "Portfolio is public" on public.portfolios;
create policy "Portfolio is public" on public.portfolios
  for select to anon, authenticated using (true);
drop policy if exists "Authenticated admins manage portfolio" on public.portfolios;
create policy "Authenticated admins manage portfolio" on public.portfolios
  for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  title text not null,
  content text not null,
  file_url text,
  status text not null default '대기중',
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;
drop policy if exists "Visitors can submit inquiries" on public.inquiries;
revoke insert on public.inquiries from anon, authenticated;
drop policy if exists "Authenticated admins read inquiries" on public.inquiries;
create policy "Authenticated admins read inquiries"
  on public.inquiries for select to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "Authenticated admins update inquiries" on public.inquiries;
create policy "Authenticated admins update inquiries"
  on public.inquiries for update to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Private inquiry attachments, uploaded only after the Edge Function validates the submission and rate limit.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('inquiry-files', 'inquiry-files', false, 10485760, array['application/pdf', 'image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = 10485760,
  allowed_mime_types = array['application/pdf', 'image/jpeg', 'image/png', 'image/webp'];

drop policy if exists "Visitors upload inquiry attachments" on storage.objects;
drop policy if exists "Authenticated admins read inquiry attachments" on storage.objects;
create policy "Authenticated admins read inquiry attachments"
  on storage.objects for select to authenticated
  using (bucket_id = 'inquiry-files' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Public portfolio assets. Anyone can view public URLs; only admins can upload or remove files.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portfolio-assets', 'portfolio-assets', true, 52428800,
  array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = 52428800,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];

drop policy if exists "Admins upload portfolio assets" on storage.objects;
create policy "Admins upload portfolio assets" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'portfolio-assets' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
drop policy if exists "Admins read portfolio asset metadata" on storage.objects;
create policy "Admins read portfolio asset metadata" on storage.objects
  for select to authenticated using (
    bucket_id = 'portfolio-assets' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
drop policy if exists "Admins update portfolio assets" on storage.objects;
create policy "Admins update portfolio assets" on storage.objects
  for update to authenticated using (
    bucket_id = 'portfolio-assets' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  ) with check (
    bucket_id = 'portfolio-assets' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );
drop policy if exists "Admins delete portfolio assets" on storage.objects;
create policy "Admins delete portfolio assets" on storage.objects
  for delete to authenticated using (
    bucket_id = 'portfolio-assets' and (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

-- Three inquiry attempts per IP fingerprint per 15 minutes. Only the Edge Function can call this.
create table if not exists public.inquiry_rate_limits (
  fingerprint text primary key,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 0
);
alter table public.inquiry_rate_limits enable row level security;
revoke all on public.inquiry_rate_limits from public, anon, authenticated;

create or replace function public.consume_inquiry_limit(p_fingerprint text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare current_attempts integer;
begin
  delete from public.inquiry_rate_limits where window_started_at < now() - interval '24 hours';
  insert into public.inquiry_rate_limits as limits (fingerprint, window_started_at, attempts)
  values (p_fingerprint, now(), 1)
  on conflict (fingerprint) do update set
    attempts = case when limits.window_started_at < now() - interval '15 minutes' then 1 else limits.attempts + 1 end,
    window_started_at = case when limits.window_started_at < now() - interval '15 minutes' then now() else limits.window_started_at end
  returning attempts into current_attempts;
  return current_attempts <= 3;
end;
$$;
revoke all on function public.consume_inquiry_limit(text) from public, anon, authenticated;
grant execute on function public.consume_inquiry_limit(text) to service_role;

grant select on public.notices to anon, authenticated;
grant insert, update, delete on public.notices to authenticated;
grant select on public.portfolios to anon, authenticated;
grant insert, update, delete on public.portfolios to authenticated;
grant select, update on public.inquiries to authenticated;
